export const frutasEnum = {
  1: "Abacaxi",
  2: "Goiaba",
  3: "Umbu",
  4: "Tangerina",
  5: "Açaí",
  6: "Graviola",
  7: "Uva",
  8: "Bacuri",
  9: "Acerola",
  10: "Maracujá",
  11: "Tamarindo",
  12: "UmbuCajá",
  13: "Manga",
  14: "Morango",
  15: "Laranja",
  16: "Cajá",
  17: "Cupuaçu",
  18: "Mangaba",
  19: "Limão",
  20: "Caju",
  21: "Jaca",
  22: "Outro"
};